name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: sleep
        run: sleep 5s

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: module install
        run: go get -u github.com/kyoh86/richgo

      - name: Test
        run: richgo test ./... -v